### ISSUE TITLE
selesnick package

### ISSUE THREAD

**Issue by janden** [scatnet/scatnet#48]
Right now, we have the selesnick package installed under filters/selesnick.

Depending on the licenses, this may or may not be allowed. What might be necessary is to point to a download link on the website and give instructions on how to link them toghether, like with libsvm.

Another option, which I think would be better, would be to roll our own versions of these methods, creating a self-contained selesnick implementation.

**Comment by matthew-hirn** [comment]
I did a quick search on Selesnick's website and could not find anything about the license. Maybe we can just ask them - say we are using their code in the ScatNet software, can we include it in the public release of the ScatNet package? Of course we would point users to their website and give them full credit (see for example the doc).

**Comment by janden** [comment]
Yeah I don't think we can include the code unless they give an OK. Honestly, though, if we have the formulas, it shouldn't be too difficult to write our own code that's more tightly integrated. What is the reference for these wavelets?

**Comment by matthew-hirn** [comment]
We will have to ask Joan for the reference on the wavelets, I just have the website. Before we go down that road though, I have emailed Selesnick asking if it is okay to include the package. I did a more thorough check of the website and of each file that is downloaded in their package, and I did not see any mention of copyright or license. Still though, I would like to get the okay from them. Nevertheless, since I did not see any restrictions, the way the email is worded is that if they don't respond, we are taking that to mean that it is okay to include them in ScatNet.

**Comment by matthew-hirn** [comment]
I heard back from Selesnick and he said we can include their software in ScatNet, just give them credit and point people to their website (as I said we would). So this information is already in the doc, but should we also include it on the website? Something like the reference to LIBSVM, although of course users will not have to download and install in this case.
