### ISSUE TITLE
Octave (as an alternative to Matlab) support?

### ISSUE THREAD

**Issue by g2boojum** [scatnet/scatnet#61]
Has anybody tried using the scatnet code with Octave instead of Matlab?  Is there any long-term desire to make the code compatible with both?  Thanks!

**Comment by eyalto** [comment]
I'm also interested to know if there is an option to use scatnet over Octav ?

**Comment by lostanlen** [comment]
Octave is not used in our lab, except when using an Octave library that does not run in MATLAB. I am not proficient enough at Octave to tell which parts of the toolbox will require to be adapted. The front-end 
'''matlab
[S,U] = scat(x,Wop)
'''
will crash because the cell array 'Wop' (for "wavelet operator") contains closures, that is, anonymous function handles with lexical scoping. I don't think that Octave allows this ; but it can be avoided quite easily by replacing 'scat' with the pipeline you want, in terms of 'wavelet_factory_1d' (or '2d') and so forth.
The new MATLAB version of ScatNet will released without any calls to anonymous functions, so I think that it will lead to better cross-compatibility with Octave.
There is a long-term will to develop a version of the toolbox in a free language, while remaining as fast and generic as the MATLAB implementation, if not more.

**Comment by lostanlen** [comment]
Octave is not used in our lab, except when using an Octave library that does not run in MATLAB. I am not proficient enough at Octave to tell which parts of the toolbox will require to be adapted. The front-end 
'''matlab
[S,U] = scat(x,Wop)
'''
will crash because the cell array 'Wop' (for "wavelet operator") contains closures, that is, anonymous function handles with lexical scoping. I don't think that Octave allows this ; but it can be avoided quite easily by replacing 'scat' with the pipeline you want, in terms of 'wavelet_factory_1d' (or '2d') and so forth.
The new MATLAB version of ScatNet will released without any calls to anonymous functions, so I think that it will lead to better cross-compatibility with Octave.
There is a long-term will to develop a version of the toolbox in a free language, while remaining as fast and generic as the MATLAB implementation, if not more.

**Comment by lostanlen** [comment]
Octave is not used in our lab, except when using an Octave library that does not run in MATLAB. I am not proficient enough at Octave to tell which parts of the toolbox will require to be adapted. The front-end 
'''matlab
[S,U] = scat(x,Wop)
'''
will crash because the cell array 'Wop' (for "wavelet operator") contains closures, that is, anonymous function handles with lexical scoping. I don't think that Octave allows this ; but it can be avoided quite easily by replacing 'scat' with the pipeline you want, in terms of 'wavelet_factory_1d' (or '2d') and so forth.
The new MATLAB version of ScatNet will released without any calls to anonymous functions, so I think that it will lead to better cross-compatibility with Octave.
There is a long-term will to develop a version of the toolbox in a free language, while remaining as fast and generic as the MATLAB implementation, if not more.

**Comment by lostanlen** [comment]
EDIT : I meant 'wavelet_layer_1d' and not 'wavelet_factory_1d'.
